// TODO Border von Panels entfernen (am Ende)
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jstratego.gui.game;

/**
 *
 * @author Tim
 */
//TODO Labels in F00, F01 ... umbenennen

public class PlayBoard extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public PlayBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        f00 = new javax.swing.JLabel();
        f01 = new javax.swing.JLabel();
        f02 = new javax.swing.JLabel();
        f03 = new javax.swing.JLabel();
        f04 = new javax.swing.JLabel();
        f06 = new javax.swing.JLabel();
        f07 = new javax.swing.JLabel();
        f05 = new javax.swing.JLabel();
        f09 = new javax.swing.JLabel();
        f08 = new javax.swing.JLabel();
        f10 = new javax.swing.JLabel();
        f15 = new javax.swing.JLabel();
        f14 = new javax.swing.JLabel();
        f13 = new javax.swing.JLabel();
        f12 = new javax.swing.JLabel();
        f11 = new javax.swing.JLabel();
        f17 = new javax.swing.JLabel();
        f16 = new javax.swing.JLabel();
        f19 = new javax.swing.JLabel();
        f18 = new javax.swing.JLabel();
        f37 = new javax.swing.JLabel();
        f38 = new javax.swing.JLabel();
        f32 = new javax.swing.JLabel();
        f31 = new javax.swing.JLabel();
        f34 = new javax.swing.JLabel();
        f33 = new javax.swing.JLabel();
        f30 = new javax.swing.JLabel();
        f35 = new javax.swing.JLabel();
        f29 = new javax.swing.JLabel();
        f28 = new javax.swing.JLabel();
        f39 = new javax.swing.JLabel();
        f20 = new javax.swing.JLabel();
        f36 = new javax.swing.JLabel();
        f25 = new javax.swing.JLabel();
        f24 = new javax.swing.JLabel();
        f23 = new javax.swing.JLabel();
        f22 = new javax.swing.JLabel();
        f21 = new javax.swing.JLabel();
        f27 = new javax.swing.JLabel();
        f26 = new javax.swing.JLabel();
        f44 = new javax.swing.JLabel();
        f41 = new javax.swing.JLabel();
        f47 = new javax.swing.JLabel();
        f42 = new javax.swing.JLabel();
        f56 = new javax.swing.JLabel();
        f54 = new javax.swing.JLabel();
        f59 = new javax.swing.JLabel();
        f51 = new javax.swing.JLabel();
        f57 = new javax.swing.JLabel();
        f50 = new javax.swing.JLabel();
        f46 = new javax.swing.JLabel();
        f45 = new javax.swing.JLabel();
        f58 = new javax.swing.JLabel();
        f48 = new javax.swing.JLabel();
        f52 = new javax.swing.JLabel();
        f40 = new javax.swing.JLabel();
        f55 = new javax.swing.JLabel();
        f53 = new javax.swing.JLabel();
        f49 = new javax.swing.JLabel();
        f43 = new javax.swing.JLabel();
        f76 = new javax.swing.JLabel();
        f65 = new javax.swing.JLabel();
        f79 = new javax.swing.JLabel();
        f60 = new javax.swing.JLabel();
        f62 = new javax.swing.JLabel();
        f64 = new javax.swing.JLabel();
        f63 = new javax.swing.JLabel();
        f84 = new javax.swing.JLabel();
        f66 = new javax.swing.JLabel();
        f67 = new javax.swing.JLabel();
        f61 = new javax.swing.JLabel();
        f77 = new javax.swing.JLabel();
        f78 = new javax.swing.JLabel();
        f72 = new javax.swing.JLabel();
        f71 = new javax.swing.JLabel();
        f74 = new javax.swing.JLabel();
        f73 = new javax.swing.JLabel();
        f70 = new javax.swing.JLabel();
        f75 = new javax.swing.JLabel();
        f68 = new javax.swing.JLabel();
        f69 = new javax.swing.JLabel();
        f95 = new javax.swing.JLabel();
        f80 = new javax.swing.JLabel();
        f92 = new javax.swing.JLabel();
        f88 = new javax.swing.JLabel();
        f98 = new javax.swing.JLabel();
        f83 = new javax.swing.JLabel();
        f93 = new javax.swing.JLabel();
        f89 = new javax.swing.JLabel();
        f99 = new javax.swing.JLabel();
        f94 = new javax.swing.JLabel();
        f87 = new javax.swing.JLabel();
        f81 = new javax.swing.JLabel();
        f96 = new javax.swing.JLabel();
        f82 = new javax.swing.JLabel();
        f97 = new javax.swing.JLabel();
        f90 = new javax.swing.JLabel();
        f86 = new javax.swing.JLabel();
        f85 = new javax.swing.JLabel();
        f91 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel102 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        f00.setBackground(java.awt.Color.white);
        f00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f00.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(f00, gridBagConstraints);

        f01.setBackground(java.awt.Color.white);
        f01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f01, gridBagConstraints);

        f02.setBackground(java.awt.Color.white);
        f02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f02.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f02, gridBagConstraints);

        f03.setBackground(java.awt.Color.white);
        f03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f03.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        f03.setName("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f03, gridBagConstraints);

        f04.setBackground(java.awt.Color.white);
        f04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f04.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f04, gridBagConstraints);

        f06.setBackground(java.awt.Color.white);
        f06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f06.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f06, gridBagConstraints);

        f07.setBackground(java.awt.Color.white);
        f07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f07.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f07, gridBagConstraints);

        f05.setBackground(java.awt.Color.white);
        f05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f05.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f05, gridBagConstraints);

        f09.setBackground(java.awt.Color.white);
        f09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f09.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel1.add(f09, gridBagConstraints);

        f08.setBackground(java.awt.Color.white);
        f08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f08.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(f08, gridBagConstraints);

        f10.setBackground(java.awt.Color.white);
        f10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f10, gridBagConstraints);

        f15.setBackground(java.awt.Color.white);
        f15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f15, gridBagConstraints);

        f14.setBackground(java.awt.Color.white);
        f14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f14, gridBagConstraints);

        f13.setBackground(java.awt.Color.white);
        f13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f13, gridBagConstraints);

        f12.setBackground(java.awt.Color.white);
        f12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f12, gridBagConstraints);

        f11.setBackground(java.awt.Color.white);
        f11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f11, gridBagConstraints);

        f17.setBackground(java.awt.Color.white);
        f17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f17, gridBagConstraints);

        f16.setBackground(java.awt.Color.white);
        f16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f16, gridBagConstraints);

        f19.setBackground(java.awt.Color.white);
        f19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f19, gridBagConstraints);

        f18.setBackground(java.awt.Color.white);
        f18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f18, gridBagConstraints);

        f37.setBackground(java.awt.Color.white);
        f37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f37, gridBagConstraints);

        f38.setBackground(java.awt.Color.white);
        f38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f38, gridBagConstraints);

        f32.setBackground(java.awt.Color.white);
        f32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f32, gridBagConstraints);

        f31.setBackground(java.awt.Color.white);
        f31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f31, gridBagConstraints);

        f34.setBackground(java.awt.Color.white);
        f34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f34, gridBagConstraints);

        f33.setBackground(java.awt.Color.white);
        f33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f33, gridBagConstraints);

        f30.setBackground(java.awt.Color.white);
        f30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f30, gridBagConstraints);

        f35.setBackground(java.awt.Color.white);
        f35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f35, gridBagConstraints);

        f29.setBackground(java.awt.Color.white);
        f29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f29, gridBagConstraints);

        f28.setBackground(java.awt.Color.white);
        f28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f28, gridBagConstraints);

        f39.setBackground(java.awt.Color.white);
        f39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f39, gridBagConstraints);

        f20.setBackground(java.awt.Color.white);
        f20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f20, gridBagConstraints);

        f36.setBackground(java.awt.Color.white);
        f36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f36, gridBagConstraints);

        f25.setBackground(java.awt.Color.white);
        f25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f25, gridBagConstraints);

        f24.setBackground(java.awt.Color.white);
        f24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f24, gridBagConstraints);

        f23.setBackground(java.awt.Color.white);
        f23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f23, gridBagConstraints);

        f22.setBackground(java.awt.Color.white);
        f22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f22, gridBagConstraints);

        f21.setBackground(java.awt.Color.white);
        f21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f21, gridBagConstraints);

        f27.setBackground(java.awt.Color.white);
        f27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f27, gridBagConstraints);

        f26.setBackground(java.awt.Color.white);
        f26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f26, gridBagConstraints);

        f44.setBackground(java.awt.Color.white);
        f44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f44, gridBagConstraints);

        f41.setBackground(java.awt.Color.white);
        f41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f41, gridBagConstraints);

        f47.setBackground(java.awt.Color.white);
        f47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f47, gridBagConstraints);

        f42.setBackground(java.awt.Color.white);
        f42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f42, gridBagConstraints);

        f56.setBackground(java.awt.Color.white);
        f56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f56, gridBagConstraints);

        f54.setBackground(java.awt.Color.white);
        f54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f54, gridBagConstraints);

        f59.setBackground(java.awt.Color.white);
        f59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f59, gridBagConstraints);

        f51.setBackground(java.awt.Color.white);
        f51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f51, gridBagConstraints);

        f57.setBackground(java.awt.Color.white);
        f57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f57, gridBagConstraints);

        f50.setBackground(java.awt.Color.white);
        f50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f50, gridBagConstraints);

        f46.setBackground(java.awt.Color.white);
        f46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f46, gridBagConstraints);

        f45.setBackground(java.awt.Color.white);
        f45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f45, gridBagConstraints);

        f58.setBackground(java.awt.Color.white);
        f58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f58, gridBagConstraints);

        f48.setBackground(java.awt.Color.white);
        f48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f48, gridBagConstraints);

        f52.setBackground(java.awt.Color.white);
        f52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f52, gridBagConstraints);

        f40.setBackground(java.awt.Color.white);
        f40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f40, gridBagConstraints);

        f55.setBackground(java.awt.Color.white);
        f55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f55, gridBagConstraints);

        f53.setBackground(java.awt.Color.white);
        f53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f53, gridBagConstraints);

        f49.setBackground(java.awt.Color.white);
        f49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f49, gridBagConstraints);

        f43.setBackground(java.awt.Color.white);
        f43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f43, gridBagConstraints);

        f76.setBackground(java.awt.Color.white);
        f76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f76.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f76, gridBagConstraints);

        f65.setBackground(java.awt.Color.white);
        f65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f65, gridBagConstraints);

        f79.setBackground(java.awt.Color.white);
        f79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f79.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f79, gridBagConstraints);

        f60.setBackground(java.awt.Color.white);
        f60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f60, gridBagConstraints);

        f62.setBackground(java.awt.Color.white);
        f62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f62, gridBagConstraints);

        f64.setBackground(java.awt.Color.white);
        f64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f64, gridBagConstraints);

        f63.setBackground(java.awt.Color.white);
        f63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f63, gridBagConstraints);

        f84.setBackground(java.awt.Color.white);
        f84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f84.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f84, gridBagConstraints);

        f66.setBackground(java.awt.Color.white);
        f66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f66, gridBagConstraints);

        f67.setBackground(java.awt.Color.white);
        f67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f67, gridBagConstraints);

        f61.setBackground(java.awt.Color.white);
        f61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f61, gridBagConstraints);

        f77.setBackground(java.awt.Color.white);
        f77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f77.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f77, gridBagConstraints);

        f78.setBackground(java.awt.Color.white);
        f78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f78.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f78, gridBagConstraints);

        f72.setBackground(java.awt.Color.white);
        f72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f72, gridBagConstraints);

        f71.setBackground(java.awt.Color.white);
        f71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f71.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f71, gridBagConstraints);

        f74.setBackground(java.awt.Color.white);
        f74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f74.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f74, gridBagConstraints);

        f73.setBackground(java.awt.Color.white);
        f73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f73.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f73, gridBagConstraints);

        f70.setBackground(java.awt.Color.white);
        f70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f70.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f70, gridBagConstraints);

        f75.setBackground(java.awt.Color.white);
        f75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f75.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f75, gridBagConstraints);

        f68.setBackground(java.awt.Color.white);
        f68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f68, gridBagConstraints);

        f69.setBackground(java.awt.Color.white);
        f69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f69.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f69, gridBagConstraints);

        f95.setBackground(java.awt.Color.white);
        f95.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f95.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f95, gridBagConstraints);

        f80.setBackground(java.awt.Color.white);
        f80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f80.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(f80, gridBagConstraints);

        f92.setBackground(java.awt.Color.white);
        f92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f92.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f92, gridBagConstraints);

        f88.setBackground(java.awt.Color.white);
        f88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f88.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f88, gridBagConstraints);

        f98.setBackground(java.awt.Color.white);
        f98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f98.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f98, gridBagConstraints);

        f83.setBackground(java.awt.Color.white);
        f83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f83.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f83, gridBagConstraints);

        f93.setBackground(java.awt.Color.white);
        f93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f93.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f93, gridBagConstraints);

        f89.setBackground(java.awt.Color.white);
        f89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f89.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(f89, gridBagConstraints);

        f99.setBackground(java.awt.Color.white);
        f99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f99.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jPanel1.add(f99, gridBagConstraints);

        f94.setBackground(java.awt.Color.white);
        f94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f94.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f94, gridBagConstraints);

        f87.setBackground(java.awt.Color.white);
        f87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f87.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f87, gridBagConstraints);

        f81.setBackground(java.awt.Color.white);
        f81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f81.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f81, gridBagConstraints);

        f96.setBackground(java.awt.Color.white);
        f96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f96.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f96, gridBagConstraints);

        f82.setBackground(java.awt.Color.white);
        f82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f82.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f82, gridBagConstraints);

        f97.setBackground(java.awt.Color.white);
        f97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f97.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f97, gridBagConstraints);

        f90.setBackground(java.awt.Color.white);
        f90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f90.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jPanel1.add(f90, gridBagConstraints);

        f86.setBackground(java.awt.Color.white);
        f86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f86.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f86, gridBagConstraints);

        f85.setBackground(java.awt.Color.white);
        f85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f85.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(f85, gridBagConstraints);

        f91.setBackground(java.awt.Color.white);
        f91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N
        f91.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel1.add(f91, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(394, 712));

        jLabel102.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("Logo");
        jLabel102.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Zug ausführen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("Neues Spiel starten");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel138.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel138.setText("zu platzieren:");

        jLabel139.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel139.setText("Feldmarschall");

        jLabel143.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel143.setText("Feldmarschall");

        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel137.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel137.setText("Feldmarschall");

        jLabel144.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel144.setText("zu platzieren:");

        jLabel118.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel135.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel135.setText("Feldmarschall");

        jLabel142.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel142.setText("zu platzieren:");

        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel124.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel124.setText("zu platzieren:");

        jLabel140.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel140.setText("zu platzieren:");

        jLabel119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel141.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel141.setText("Feldmarschall");

        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel123.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel123.setText("Feldmarschall");

        jLabel136.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel136.setText("zu platzieren:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel121)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel123)
                            .addComponent(jLabel124)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel113)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel135)
                            .addComponent(jLabel136)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel120)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel137)
                            .addComponent(jLabel138)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel105)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel139)
                            .addComponent(jLabel140)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel119)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel141)
                            .addComponent(jLabel142)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel118)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel143)
                            .addComponent(jLabel144))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel121)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel123)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel124)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel113)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel135)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel136)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel120)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel137)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel138)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel105)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel139)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel140)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel119)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel141)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel142)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel118)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel143)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel144)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel129.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel129.setText("Feldmarschall");

        jLabel134.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel134.setText("zu platzieren:");

        jLabel133.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel133.setText("Feldmarschall");

        jLabel128.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel128.setText("zu platzieren:");

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel122.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel122.setText("zu platzieren:");

        jLabel125.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel125.setText("Feldmarschall");

        jLabel131.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel131.setText("Feldmarschall");

        jLabel127.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel127.setText("Feldmarschall");

        jLabel126.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel126.setText("zu platzieren:");

        jLabel132.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel132.setText("zu platzieren:");

        jLabel108.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel108.setText("Feldmarschall");

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        jLabel130.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel130.setText("zu platzieren:");

        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jstratego/gui/img/missing.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel101)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel108)
                            .addComponent(jLabel122)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel112)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel125)
                            .addComponent(jLabel126)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel103)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel127)
                            .addComponent(jLabel128)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel104)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel129)
                            .addComponent(jLabel130)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel107)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel131)
                            .addComponent(jLabel132)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel106)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel133)
                            .addComponent(jLabel134))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel101)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel108)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel122)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel112)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel125)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel126)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel103)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel127)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel128)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel104)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel129)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel130)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel107)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel131)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel132)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel106)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel133)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel134)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlayBoard().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f00;
    private javax.swing.JLabel f01;
    private javax.swing.JLabel f02;
    private javax.swing.JLabel f03;
    private javax.swing.JLabel f04;
    private javax.swing.JLabel f05;
    private javax.swing.JLabel f06;
    private javax.swing.JLabel f07;
    private javax.swing.JLabel f08;
    private javax.swing.JLabel f09;
    private javax.swing.JLabel f10;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f12;
    private javax.swing.JLabel f13;
    private javax.swing.JLabel f14;
    private javax.swing.JLabel f15;
    private javax.swing.JLabel f16;
    private javax.swing.JLabel f17;
    private javax.swing.JLabel f18;
    private javax.swing.JLabel f19;
    private javax.swing.JLabel f20;
    private javax.swing.JLabel f21;
    private javax.swing.JLabel f22;
    private javax.swing.JLabel f23;
    private javax.swing.JLabel f24;
    private javax.swing.JLabel f25;
    private javax.swing.JLabel f26;
    private javax.swing.JLabel f27;
    private javax.swing.JLabel f28;
    private javax.swing.JLabel f29;
    private javax.swing.JLabel f30;
    private javax.swing.JLabel f31;
    private javax.swing.JLabel f32;
    private javax.swing.JLabel f33;
    private javax.swing.JLabel f34;
    private javax.swing.JLabel f35;
    private javax.swing.JLabel f36;
    private javax.swing.JLabel f37;
    private javax.swing.JLabel f38;
    private javax.swing.JLabel f39;
    private javax.swing.JLabel f40;
    private javax.swing.JLabel f41;
    private javax.swing.JLabel f42;
    private javax.swing.JLabel f43;
    private javax.swing.JLabel f44;
    private javax.swing.JLabel f45;
    private javax.swing.JLabel f46;
    private javax.swing.JLabel f47;
    private javax.swing.JLabel f48;
    private javax.swing.JLabel f49;
    private javax.swing.JLabel f50;
    private javax.swing.JLabel f51;
    private javax.swing.JLabel f52;
    private javax.swing.JLabel f53;
    private javax.swing.JLabel f54;
    private javax.swing.JLabel f55;
    private javax.swing.JLabel f56;
    private javax.swing.JLabel f57;
    private javax.swing.JLabel f58;
    private javax.swing.JLabel f59;
    private javax.swing.JLabel f60;
    private javax.swing.JLabel f61;
    private javax.swing.JLabel f62;
    private javax.swing.JLabel f63;
    private javax.swing.JLabel f64;
    private javax.swing.JLabel f65;
    private javax.swing.JLabel f66;
    private javax.swing.JLabel f67;
    private javax.swing.JLabel f68;
    private javax.swing.JLabel f69;
    private javax.swing.JLabel f70;
    private javax.swing.JLabel f71;
    private javax.swing.JLabel f72;
    private javax.swing.JLabel f73;
    private javax.swing.JLabel f74;
    private javax.swing.JLabel f75;
    private javax.swing.JLabel f76;
    private javax.swing.JLabel f77;
    private javax.swing.JLabel f78;
    private javax.swing.JLabel f79;
    private javax.swing.JLabel f80;
    private javax.swing.JLabel f81;
    private javax.swing.JLabel f82;
    private javax.swing.JLabel f83;
    private javax.swing.JLabel f84;
    private javax.swing.JLabel f85;
    private javax.swing.JLabel f86;
    private javax.swing.JLabel f87;
    private javax.swing.JLabel f88;
    private javax.swing.JLabel f89;
    private javax.swing.JLabel f90;
    private javax.swing.JLabel f91;
    private javax.swing.JLabel f92;
    private javax.swing.JLabel f93;
    private javax.swing.JLabel f94;
    private javax.swing.JLabel f95;
    private javax.swing.JLabel f96;
    private javax.swing.JLabel f97;
    private javax.swing.JLabel f98;
    private javax.swing.JLabel f99;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
